apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: utoxfei56-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: utoxfei56-go 
  name: utoxfei56-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: utoxfei56-go 
